
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

# Ctrl+Shift+C を SIGINT (Ctrl+C は Copy に取られているので代替)
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
chars = "\u0003"
