--enable-features=VaapiVideoDecodeLinuxGL,UseOzonePlatform
--ozone-platform=wayland
--enable-gpu-rasterization
--enable-zero-copy
--ignore-gpu-blocklist
# NVIDIA + Wayland で Google Meet の背景ぼかしが真っ白になるのを回避
--disable-gpu-compositing
