context.modules = [
    { name = libpipewire-module-echo-cancel
        args = {
            node.description = "Echo & Noise Cancelling Source"
            media.name = "Echo & Noise Cancelling Source"
            monitor.mode = true
            aec.method = webrtc
            capture.props = {
                node.name = "ec_capture"
                node.target = "alsa_input.usb-BurrBrown_from_Texas_Instruments_USB_AUDIO_CODEC-00.analog-stereo"

                audio.rate = 48000
            }
            source.props = {
                node.name = "ec_source"

                audio.rate = 48000
            }
            sink.props = {
                node.name = "ec_sink"

                audio.rate = 48000
            }
            playback.props = {
                node.name = "ec_playback"

                audio.rate = 48000
            }
        }
    }
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "Noise Cancelling Source"
            media.name = "Noise Cancelling Source"
            filter.graph = {
                nodes = [
                    {
                        type  = ladspa
                        name  = rnnoise
                        plugin = librnnoise_ladspa
                        label = noise_suppressor_mono
                        control = {
                            "VAD Threshold (%)" = 30.0
                            "VAD Grace Period (ms)" = 200
                            "Retroactive VAD Grace (ms)" = 0
                        }
                    }
                    {
                        type  = builtin
                        name  = gain
                        label = mixer
                        control = {
                            "Gain 1" = 4.0
                        }
                    }
                ]
                links = [
                    { output = "rnnoise:Output" input = "gain:In 1" }
                ]
                inputs  = [ "rnnoise:Input" ]
                outputs = [ "gain:Out" ]
            }
            capture.props = {
                node.name = "capture.rnnoise_source"
                node.target = "ec_source"

                audio.rate = 48000
            }
            playback.props = {
                node.name = "rnnoise_source"
                media.class = Audio/Source

                audio.rate = 48000
            }
        }
    }
]
